spring:
  redis:
    #    timeout: 2000
    #    host: 127.0.0.1
    #    port: 6379

    #    port: 6379
    #    host: 127.0.0.1
    #    lettuce:
    #      pool:
    #        max-active: -1
    #        max-idle: 2000
    #        max-wait: -1
    #        min-idle: 1
    #        time-between-eviction-runs: 5000
    redisson:
      file: classpath:redisson.yml
